using ScalarScope.Models;
using ScalarScope.Services;
using System.Text;

namespace ScalarScope.Services;

/// <summary>
/// Phase 5.4: Generate copy-ready cards for sharing deltas.
/// </summary>
public static class DeltaCopyService
{
    /// <summary>
    /// Generate a plain-text copy card for a delta.
    /// </summary>
    public static string GeneratePlainTextCard(CanonicalDelta delta)
    {
        var sb = new StringBuilder();
        
        // Header with emoji based on delta type
        var emoji = GetDeltaEmoji(delta.DeltaType);
        sb.AppendLine($"{emoji} {delta.Name}");
        sb.AppendLine(new string('─', 30));
        
        // Main explanation
        sb.AppendLine(delta.Explanation);
        sb.AppendLine();
        
        // Values
        sb.AppendLine($"📊 Path A: {FormatValue(delta.LeftValue, delta.Units)}");
        sb.AppendLine($"📊 Path B: {FormatValue(delta.RightValue, delta.Units)}");
        sb.AppendLine($"📐 Δ: {FormatValue(delta.Delta, delta.Units)} ({GetDirection(delta.Delta)})");
        sb.AppendLine();
        
        // Confidence
        var tier = ConfidenceTokens.GetTierFromConfidence(delta.Confidence);
        var confidenceLabel = ConfidenceTokens.GetLabel(tier);
        sb.AppendLine($"🎯 Confidence: {confidenceLabel} ({delta.Confidence:P0})");
        
        // Visual anchor
        sb.AppendLine($"📍 Visible at: {delta.VisualAnchorTime:P0} of timeline");
        
        sb.AppendLine();
        sb.AppendLine("─ ScalarScope Analysis");
        
        return sb.ToString();
    }
    
    /// <summary>
    /// Generate a Markdown copy card for a delta.
    /// </summary>
    public static string GenerateMarkdownCard(CanonicalDelta delta)
    {
        var sb = new StringBuilder();
        
        // Header
        var emoji = GetDeltaEmoji(delta.DeltaType);
        sb.AppendLine($"### {emoji} {delta.Name}");
        sb.AppendLine();
        
        // Main explanation
        sb.AppendLine($"> {delta.Explanation}");
        sb.AppendLine();
        
        // Table of values
        sb.AppendLine("| Metric | Value |");
        sb.AppendLine("|--------|-------|");
        sb.AppendLine($"| Path A | {FormatValue(delta.LeftValue, delta.Units)} |");
        sb.AppendLine($"| Path B | {FormatValue(delta.RightValue, delta.Units)} |");
        sb.AppendLine($"| Delta | {FormatValue(delta.Delta, delta.Units)} ({GetDirection(delta.Delta)}) |");
        sb.AppendLine($"| Confidence | {ConfidenceTokens.GetLabel(ConfidenceTokens.GetTierFromConfidence(delta.Confidence))} |");
        sb.AppendLine();
        
        // Footer
        sb.AppendLine($"*Visible at {delta.VisualAnchorTime:P0} of timeline • ScalarScope*");
        
        return sb.ToString();
    }
    
    /// <summary>
    /// Generate a summary card for multiple deltas.
    /// </summary>
    public static string GenerateSummaryCard(IEnumerable<CanonicalDelta> deltas)
    {
        var deltaList = deltas.Where(d => d.Status == DeltaStatus.Present).ToList();
        if (deltaList.Count == 0)
            return "No significant differences detected between the runs.";
        
        var sb = new StringBuilder();
        sb.AppendLine("## ScalarScope Comparison Summary");
        sb.AppendLine();
        sb.AppendLine($"**{deltaList.Count} differences detected:**");
        sb.AppendLine();
        
        foreach (var delta in deltaList)
        {
            var emoji = GetDeltaEmoji(delta.DeltaType);
            var tier = ConfidenceTokens.GetTierFromConfidence(delta.Confidence);
            var badge = tier switch
            {
                ConfidenceTokens.ConfidenceTier.High => "🟢",
                ConfidenceTokens.ConfidenceTier.Medium => "🟡",
                ConfidenceTokens.ConfidenceTier.Low => "🟠",
                _ => "⚪"
            };
            sb.AppendLine($"- {emoji} **{delta.Name}** {badge}");
            sb.AppendLine($"  {delta.Explanation}");
            sb.AppendLine();
        }
        
        sb.AppendLine("---");
        sb.AppendLine("*Generated by ScalarScope*");
        
        return sb.ToString();
    }
    
    /// <summary>
    /// Copy delta card to clipboard.
    /// </summary>
    public static async Task CopyToClipboardAsync(CanonicalDelta delta, bool useMarkdown = false)
    {
        var text = useMarkdown 
            ? GenerateMarkdownCard(delta) 
            : GeneratePlainTextCard(delta);
        
        await Clipboard.Default.SetTextAsync(text);
    }
    
    /// <summary>
    /// Copy summary card to clipboard.
    /// </summary>
    public static async Task CopySummaryToClipboardAsync(IEnumerable<CanonicalDelta> deltas)
    {
        var text = GenerateSummaryCard(deltas);
        await Clipboard.Default.SetTextAsync(text);
    }
    
    private static string GetDeltaEmoji(DeltaType type) => type switch
    {
        DeltaType.Event => "⚠️",
        DeltaType.Timing => "⏱️",
        DeltaType.Structure => "🔷",
        DeltaType.Behavior => "📈",
        _ => "🔹"
    };
    
    private static string FormatValue(double value, string? units)
    {
        var formatted = Math.Abs(value) < 0.01 || Math.Abs(value) > 1000
            ? value.ToString("G3")
            : value.ToString("F2");
        
        return string.IsNullOrEmpty(units) ? formatted : $"{formatted} {units}";
    }
    
    private static string GetDirection(double delta) => delta switch
    {
        > 0 => "↑",
        < 0 => "↓",
        _ => "="
    };
}
